title = "Cities in Dust"
baseURL = "/"
languageCode = "de-DE"
theme = "blank"

# enableGitInfo = true

DefaultContentLanguage = "de"

# [frontmatter]
#   lastmod = [":git", "lastmod"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]

[params]
  mainSections = ["articles"]
  eventSections = ["others", "festivals", "parties", "concerts"]