title = "Cities in Dust"
baseURL = "/"
languageCode = "de-DE"
theme = "blank"

# enableGitInfo = true

DefaultContentLanguage = "de"
timeZone = "Europe/Berlin"
copyright = "Design / Programmierung: <a href=\"https://angel-crawford.de/\" target=\"_blank\">Angel Crawford</a>.<br />Alle Rechte vorbehalten."

# [frontmatter]
#   lastmod = [":git", "lastmod"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = "0.9"
  filename = "sitemap.xml"

[params]
  mainSections = ["messages"]

  author = "Angel Crawford"
  favicon = "favicon.ico"
  description = "The last theme you'll ever need. Maybe. dsds"

  [params.seo]
    twitterHandle = "crawford_ftw" #Twitter name, to bind shared cards to your profile
    keywords = "Webcard, Profil Karte, Angel Crawford"

  [[params.social]]
    name = "Facebook"
    link = "https://facebook.com"
    icon = "facebook-circle-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "twitter-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Instagram"
    link = "#"
    icon = "instagram-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "Github"
    link = "#"
    icon = "github-line"
    inHeader = false
    inFooter = true
  [[params.social]]
    name = "RSS"
    link = "/index.xml"
    icon = "rss-line"
    inHeader = true
    inFooter = true
