title = "Cities in Dust"
baseURL = "/"
languageCode = "de-DE"
theme = "blank"

# enableGitInfo = true

DefaultContentLanguage = "de"
timeZone = "Europe/Berlin"
copyright = "Design / Programmierung: <a href=\"https://angel-crawford.de/\" target=\"_blank\">Angel Crawford</a>.<br />Alle Rechte vorbehalten."

# [frontmatter]
#   lastmod = [":git", "lastmod"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]

[params]
  mainSections = ["articles"]
  eventSections = ["others", "festivals", "parties", "concerts"]

[sitemap]
  changefreq = "weekly"
  priority = "0.9"
  filename = "sitemap.xml"
